defmodule ExposureWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :exposure

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_exposure_key",
    signing_salt: "NudonHv+",
    same_site: "Lax"
  ]

  socket("/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]
  )

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.

  # Images are served from a configurable path (set via :images_path in config)
  # This allows Docker deployments to use mounted volumes
  # Default: release priv/static/images/places
  plug(Plug.Static,
    at: "/images/places",
    from: {__MODULE__, :images_path, []},
    gzip: false,
    headers: %{"cache-control" => "public, max-age=86400"}
  )

  @doc false
  def images_path do
    Application.get_env(:exposure, :images_path) ||
      Application.app_dir(:exposure, "priv/static/images/places")
  end

  # Other static assets (JS, CSS, fonts, etc.)
  plug(Plug.Static,
    at: "/",
    from: :exposure,
    gzip: not code_reloading?,
    only: ExposureWeb.static_paths(),
    raise_on_missing_only: code_reloading?
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket("/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket)
    plug(Phoenix.LiveReloader)
    plug(Phoenix.CodeReloader)
    plug(Phoenix.Ecto.CheckRepoStatus, otp_app: :exposure)
  end

  plug(Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
  )

  plug(Plug.RequestId)
  plug(ExposureWeb.Plugs.TraceId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # Allow up to 100MB for multipart uploads (10MB * 10 files reasonable batch)
    # This must be >= max_file_size * reasonable_batch_size
    length: 100_000_000
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(Plug.Session, @session_options)
  plug(ExposureWeb.Router)
end
